export const pepe = `                                                                                                  
                                                                                                    
                                                                                                    
                                  ......                                                            
                            .^7J5GBBBBBBGPY?~.                                                      
                        :~?5PGGPP5555555PPGBBGY!:       .^~7?JJYYYJJ7~:                             
                     :?5GP5YYYYYYYYYYYYYYYYYYY5PPY?~^!J5GGGPP55555555PP5?~:                         
                   ~5BG5YYYYYYYY5PPPGGGGGBBB#####&@&&@B5YYYYYYYYYYYYY5PGB&&B57^.                    
                 ^P#PYYYYYYYPGGGGPPP555555555555555PPGGGGGP5YYYYY5PGGBBBBGBBB#BG5?!^.               
               .J#GYYYYYY5PPP5YYYYYYYYYYYYYY555PPPPPPPPPGB&&#BP5YYYYYYYYYYYYY55PGG&&#GY7^.          
              ^GB5YYYYYYY5YYYYYYYYYYY5PGGGGGGPPPPPP55555555PPGGGBG5YY5PPPPGGGGGGGGGGGGGGGPY7~.      
             ~#BYYYYYYYYYYYYYYYY55PGGGPPPPP55YJ?7!~~^::^^^~7J5GBB&&BGGGPPPPPP55YYYYYY55PPGGGP5?:    
            .BBYYYYYYYYYYYYYYYYY555PPPPY?!^:.       .:::.     :7P&&GG5?7~^::..    .:^:..:^!?YG##:   
            !&5YYYYYYYYYYYYYY555555J7~.          :?PB#&&#P7.     !B@Y           !P####G?.    .!BY   
           :BBYYYYYYYYYYYYYYP&7:.               7#@&&&@@@&@5      :BP          Y&&&&&@@@B^     ^G.  
          7#&PYYYYYYYYYYYYYYYPPP5?^            ~&&&&&G!!J#&#.      7&:        ~@&&&#5Y5&@G      G~  
        ~5G55YYYYYYYYYYYYYYYYYYY5PB5^          ?@&&&&Y  !#@B.      ~@!        ~&&&&G^^!#&!      B!  
      ^5P5YYYYYYYYYYYYYYYYYYYYYYP5YPGY~        :G@&&&&B#@&B!       P@B7:       !G#&&&@@#7      !G.  
     7G5YYYYYYYYYYYYYYYYYYYYYYYYYGGPY5GPJ~.     .75GBGG5J~.      :P@#PGG5?!^:.   :^^~!~.     :?P.   
    YBYYYYYYYYYYYYYYYYYYYYYYYYYYYYYPGGP5PGP5J7~^:            .^!5#BB#BPY5PGGPP5YJ????77????YP##:    
   ?&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5PGGPPPPPPPPP5YJJ???JJY5PGB&GYYYPBBG55PPPGGGGGGGGGGGGGGPY^     
  .#GYYYYYYYYYYYYYYYYYYYYYYYYYYPGGP5YYYYYY5PGGGPPPPPP55555PPGGGP5YYYYYY5B#BPYYYY55PGB&&&&#J!:       
  ~&5YYYYYYYYYYYYYYYYYYYYYYYYYYY5PGBBBGGPP555555PPGGGB&&##BGP5YYYYYYYYYYY5B&&BBGGBBBB#####J.        
  ?&YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY55PPGGGGGBBBBBGGGPP5YYYYYYYYYYYYYYYYYY5B&BP555YYYYYYYPG~       
  5BYYYYYYYYYYYYYYGG5YY5PPP55YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYGGYYYYYYYYYYYY5BY:     
  BGYYYYYYYYYYYY5BPYYPGGPPPGGGGGP55YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5&B!    
 .#PYYYYYYYYYYYY5YYYBG5YYYYYY555PPGGGGGPP55YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5PGBGP#!   
 .#PYYYYYYYYYYYYYYY5&5Y5555P555YYYYY555PPGGGGGGPP5555YYYYYYYYYYYYYYYYYYYYYYYYYYYYY555PPGGGP5555P^   
 .#PYYYYYYYYYYYYYYYYBB5Y5YP&#BBBGGP555YYYYYY5555PPPGGGGGPPPPPPPP5555555PPPPPPPGGGGGPPP5555PPPJ~     
 .BPYYYYYYYYYYYYYYYYYPBP5Y5PGGGGGGGBBBGGGPP5555YYYYYYY555555PPPPPPPPPPPPPP5555555555PPGBGY?~:       
 .#GYYYYYYYYYYYYYYYYYYYPGP5YY5GBBGPPPPPGGGGGBGGGGGPPPPP55555555555555555PPPGGGGGB##GGGGBY.          
  ?&5YYYYYYYYYYYYYYYYYYYYPGP5YY55GBBBGPPPPGGGGGGGGGGGGGGGBBBBBBBBBBB###&P??77!!!!?5GG5YY5Y?:        
   !GPYYYYYYYYYYYYYYYYYYYYY5GGP5YYY5PGB##&#GPPGGB#BBGGPPPPPPPPPPPPPPPPGBB?~~~~~~~~~!?GBP5555J       
    .?PPYYYYYYYYYYYYYYYYYYYYY5PGP55YYY55PBGY?!~~~!?J5GB#BGGPPPPPPPPPPPPG&&?~~~~~~~~~^^J&B555BY      
      .7Y55YYYYYYYYYYYYYYYYYYYYY5PGGP5YYYY5PPGP5YJ7!~~!?5G##BBGGPPPPGGB#BJ~~~~~~~~~!7?5#G5YYBB      
         :7YP5YYYYYYYYYYYYYYYYYYYYY5PGGP55YYYY55PPGGGP5YJJYG&&&&&##&&#P?~~!!7?JY5PPGGP5YYY5G5:      
            ^?5P5YYYYYYYYYYYYYYYYYYYYY5PGGGGP55YYYYY5555PPPGGGGGGGGGGG5Y55PPPPPP55555Y55PBP~        
               ^7YPP5YYYYYYYYYYYYYYYYYYYYY5PGBBGGPP55YYYYYYYYYYYYYY555PPPPPPPPGPP555P##&#J.         
                  :!JPPP5YYYYYYYYYYYYYYYYYYYYYY5PPGGGGGGPPPP5PPPGGGGGPP55YYYYYYYYYYY5&#J:           
                     .^7YPPP5YYYYYYYYYYYYYYYYYYYYYYYYY555PPGGGP55YYYYYYYYYYYYY55PGGBBJ:             
                         .^!?Y5PP555YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY5555PGBGPY?!~.               
                              .:~7?YY55PPPPPPPPPPPPPPPPP55PPPPPP555PPPGGPY?7~:.                     
                                     ..::^^~~!!7777777777777??77~^:....                             
                                                                                                    
`
